from .system_prompt import (
    SYSTEM_PROMPT,
    RESUME_SYSTEM_PROMPT,
    SUMMARY_SYSTEM_PROMPT,
    SKILLS_SYSTEM_PROMPT,
    CAREER_SYSTEM_PROMPT,
    JD_SYSTEM_PROMPT,
    INTERVIEW_SYSTEM_PROMPT,
    JOB_MATCH_SYSTEM_PROMPT,
)
from .prompt_manager import prompt_manager, PromptManager

__all__ = [
    "SYSTEM_PROMPT", "RESUME_SYSTEM_PROMPT",
    "SUMMARY_SYSTEM_PROMPT", "SKILLS_SYSTEM_PROMPT",
    "CAREER_SYSTEM_PROMPT", "JD_SYSTEM_PROMPT",
    "INTERVIEW_SYSTEM_PROMPT", "JOB_MATCH_SYSTEM_PROMPT",
    "prompt_manager", "PromptManager",
]
